### ISSUE TITLE
佬，能不能放一下diy目录下的utils

### ISSUE THREAD

**Issue by bjl101501** [ccwav/QL_DIYBOT#10]
我的原版没有这个文件，这几个文件都无法加载，找了半天也没找到
![image](https://user-images.githubusercontent.com/82082262/199284716-2550007f-113f-4645-8786-312d631d616f.png)

![image](https://user-images.githubusercontent.com/82082262/199284453-021ecd4b-17fe-4ce3-a14d-1106c6223afa.png)

**Comment by ccwav** [comment]
那是diybot的，我只是自用维护，所以只提供维护的部分文件
