### ISSUE TITLE
something wrong,I'm sorry 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by chenleicpp** [ccwav/QL_DIYBOT#5]
作者您好，首先感谢您提供这么好用的脚本，我在实际试用中发现上述问题，执行全局命令，如bb、bc、bd都会出现上述错误提示(在机器人本身中输入出现，在其他群组中不会出现)，不知道如何解决这个问题，感谢

**Comment by ccwav** [comment]
没遇到过，所以不知道
